---
title: "SOPO Presentation"
output: html_notebook
---
```{r}
#Upload packages -  go through these to see which apply.
library(tidyverse)
library(here)
library(patchwork)
library(readxl)
```

```{r}
#Upload the full 5m chemtax timeseries - processing in same way as manuscript
chem <- read_csv(here("files", "combined_2024-02-07.csv"))

#POC data
poc <- read_csv(here("outputs", "poc_conversion_2024-05-13.csv"))
```

Wrangling Data

```{r}
#Working with chemtax data to make it easy to plot

#Making the date column a date format
chem <- chem %>% 
  mutate(date2 = lubridate::mdy(Date))

#Selecting appropriate columns and renaming to easy to work with names
chem <- chem %>% 
  select(date = date2, depth, cyan = Cyanobacteria, hapt = Hapto, 
         GA = `Prasinophytes-3`, cryp = Cryptophytes,
         dino = `Dinoflagellates-1`, dict = Dictyo, diat = `Diatoms-1`)

#Pivoting to long/tidy for plotting in ggplot
chem_long <- chem %>% 
  pivot_longer(c(cyan:diat), names_to = "group", values_to = "contribution")

#Calculating TChla for each sample
chem_long <- chem_long %>% 
  group_by(date, group) %>% 
  summarise(contribution = mean(contribution)) %>% 
  ungroup() %>% 
  group_by(date) %>% 
  mutate(tchla = sum(contribution)) %>% 
  ungroup()

#checking to see if there are any duplicates - there were replicates taken for DFO comparisons. None found because I already averaged these for the manuscript.
chem_dup <- chem_long %>%
  distinct(date, tchla) %>% 
  group_by(date) %>% 
  mutate(dup = n()) %>% 
  ungroup() %>% 
  filter(dup > 1)

#Good to move forward
```



```{r}
#Setting plotting order phytoplankton groups

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapt", "GA", "cryp",
                   "dino", "dict", "diat")

#Chemtax full data - Specify order of phyto groups for figures
chem_long <- arrange(mutate(chem_long,
                                group = factor(group,
                                levels = order_chem)))

```

```{r}
#Set Color palette for plotting. Currently based on QU39 manuscript. Brewer has some good ones for R style.
palette <- c("#ff8000", #1 - Diatoms (orange)
             "#ff99c7", #2 - Dictyochophytes (pink)
             #"#4d6600", #3 - Raphidophytes (dark green)
             "#ff0000", #4 - Dinoflagellates (Red)
             "#ffff00", #5 - Cryptophytes (yellow)
             "#00ff00", #6 - Chlorophyta (light green)
             "#7d4dcc", #7 - Haptophytes (purple)
             "#000000") #8 - Cyanobacteria (black)
```

```{r}
#Doing the cumulative sum for each year

#Calculating cumulative sum TChla
cu_sum <- chem_long %>%
  select(date, tchla) %>% 
  distinct() %>% 
  mutate(year = lubridate::year(date), 
         doy = lubridate::yday(date)) %>% 
  filter(!is.na(tchla)) %>% 
  mutate(median_all_tchla = median(tchla)) %>% 
  group_by(year) %>% 
  mutate(bm_total = tchla - median_all_tchla,
         bm_sum_total = cumsum(bm_total)) %>%  
  ungroup() %>% 
  mutate(doy = lubridate::yday(date))

#Selecting max value for Wiley's table
cu_sum_max_tchla <- cu_sum %>% 
  group_by(year) %>% 
  filter(bm_sum_total == max(bm_sum_total, na.rm = T)) %>% 
  ungroup()

#Selecting max value for Wiley's table
cu_sum_pos_tchla <- cu_sum %>% 
  group_by(year) %>% 
  slice(which.max(bm_sum_total > 0)) %>% 
  ungroup()
```

```{r}
#Trying the method of Racault et al. (2015) http://dx.doi.org/10.1016/j.rse.2015.01.019

#Calculate the climatological median value +10%
rac_ts_med <- chem_long %>%
  select(date, tchla) %>% 
  distinct() %>% 
  mutate(year = lubridate::year(date), 
         doy = lubridate::yday(date)) %>% 
  filter(!is.na(tchla)) %>% 
  mutate(median_all_tchla = median(tchla),
         median_10perc = (median_all_tchla*0.1) + median_all_tchla,
         anom = tchla - median_10perc) %>% 
  group_by(year) %>%
  mutate(cu_sum_anom = cumsum(anom),
         diff = cu_sum_anom - lag(cu_sum_anom, 1)) 
```

```{r}
rac_ts_med %>% 
  # filter(year == 2016) %>% 
  ggplot(aes(date, tchla)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 1.29)
```




```{r}
#Joining the cumulative sum with the chemtax data for plotting.
chem_join_plot <- chem_long %>% 
  left_join(cu_sum) 
```

```{r}
#Setting a scale factor for the right-y axis in the CHEMTAX and annual integration plot - next chunk
scale_int <- 5
```

```{r}
chem_full <- chem_join_plot %>%
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>%
  ggplot() +
  geom_area(data = filter(chem_join_plot, date > as.Date("2015-01-01") &
                            date < as.Date("2015-10-07")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 1, color = "black", size = 0.1) +
  geom_area(data = filter(chem_join_plot, date > as.Date("2015-10-07") &
                            date < as.Date("2015-11-04")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 1, color = "black", size = 0.1) +
  geom_bar(data = filter(chem_join_plot, date == as.Date("2015-11-03")),
           aes(date, contribution, fill = fct_rev(group)),
           alpha = 1, color = "black", width = 10, size = 0.1,  
           position = "stack", stat = "identity") +
  geom_area(data = filter(chem_join_plot, date > as.Date("2015-11-04") &
                            date < as.Date("2020-03-19")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 1, color = "black", size = 0.1) +
  geom_area(data = filter(chem_join_plot, date > as.Date("2020-03-19")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 1, color = "black", size = 0.1) +
  geom_point(aes(date, tchla), size = 0.3) +
  scale_fill_manual(values = palette,
                    labels = c("Diat", "Dict", "Dino", "Cryt", "GA",
                               "Hapt", "Cyan")) +
  geom_line(data = filter(chem_join_plot, date > as.Date("2015-02-23") &
                            date < as.Date("2015-10-06")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2016-04-01") &
                            date <= as.Date("2016-10-02")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2017-04-20") &
                            date <= as.Date("2017-10-11")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2018-03-20") &
                            date <= as.Date("2018-10-24")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2019-03-12") &
                            date <= as.Date("2019-11-13")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2020-03-18") &
                            date <= as.Date("2020-07-29")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2021-02-23") &
                            date <= as.Date("2021-10-19")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2022-02-18") &
                            date <= as.Date("2022-10-26")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2023-03-21") &
                            date <= as.Date("2023-11-07")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale_int,
                                         name = bquote("Annual Int. TChla (mg" ~ m^-2*")"))) +
  scale_x_date(limits = as.Date(c("2015-01-01", "2024-01-01")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%b%y") +
  theme_bw() +
  labs(y = bquote("Phyto. Comp. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(panel.grid.major.x =  element_line(color = "darkgrey", size = 0.5),
        panel.grid.minor.x =  element_line(color = "darkgrey", size = 0.5),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 30), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank()) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE))

ggsave(here("figures", "timeseries_5m_chemtax_integrated.png"),
        width = 16, height = 6, dpi = 300)
```

```{r}
chem_full <- chem_join_plot %>%
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>%
  ggplot() +
  geom_area(data = filter(chem_join_plot, date > as.Date("2015-01-01") &
                            date < as.Date("2015-10-07")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 0.9) +
  geom_area(data = filter(chem_join_plot, date > as.Date("2015-10-07") &
                            date < as.Date("2015-11-04")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 0.9) +
  geom_bar(data = filter(chem_join_plot, date == as.Date("2015-11-03")),
           aes(date, contribution, fill = fct_rev(group)),
           alpha = 0.9, color = "black", width = 10, size = 0.1,  
           position = "stack", stat = "identity") +
  geom_area(data = filter(chem_join_plot, date > as.Date("2015-11-04") &
                            date < as.Date("2020-03-19")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 0.9) +
  geom_area(data = filter(chem_join_plot, date > as.Date("2020-03-19")),
            aes(date, contribution, fill = fct_rev(group)),
            alpha = 0.9) +
  # geom_point(aes(date, tchla), size = 0.3) +
  # scale_fill_manual(values = palette,
  #                   labels = c("Diat", "Dict", "Dino", "Cryt", "GA",
  #                              "Hapt", "Cyan")) +
  ggsci::scale_fill_d3() +
  geom_line(data = filter(chem_join_plot, date > as.Date("2015-02-23") &
                            date < as.Date("2015-10-06")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2016-04-01") &
                            date <= as.Date("2016-10-02")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2017-04-20") &
                            date <= as.Date("2017-10-11")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2018-03-20") &
                            date <= as.Date("2018-10-30")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2019-03-12") &
                            date <= as.Date("2019-11-13")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2020-03-18") &
                            date <= as.Date("2020-09-22")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2021-02-23") &
                            date <= as.Date("2021-10-19")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2022-02-18") &
                            date <= as.Date("2022-10-26")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2023-03-21") &
                            date <= as.Date("2023-11-07")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale_int,
                                         name = bquote("Annual Int. TChla (mg" ~ m^-2*")")),
                     expand = c(0, 0)) +
  scale_x_date(limits = as.Date(c("2015-01-01", "2024-01-01")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%b%y") +
  theme_bw() +
  labs(y = bquote("Phyto. Comp. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(panel.grid.major.x =  element_line(color = "darkgrey", size = 0.5),
        panel.grid.minor.x =  element_line(color = "darkgrey", size = 0.5),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 30), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank()) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE))

ggsave(here("figures", "timeseries_5m_chemtax_integrated_alternative.png"),
        width = 16, height = 6, dpi = 300)
```

```{r}
chem_full <- chem_join_plot %>%
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>%
  ggplot() +
  geom_line(data = filter(chem_join_plot, date > as.Date("2015-01-01") &
                            date < as.Date("2015-10-07") & group == "diat"),
            aes(date, contribution),
            size = 1, color = "orange") +
  geom_line(data = filter(chem_join_plot, date > as.Date("2015-10-07") &
                            date < as.Date("2015-11-04") & group == "diat"),
            aes(date, contribution),
            size = 1, color = "orange") +
  # geom_point(data = filter(chem_join_plot, date == as.Date("2015-11-03") 
  #                          & group == "diat"),
  #            aes(date, contribution),
  #            color = "black", size = 3) +
  geom_line(data = filter(chem_join_plot, date > as.Date("2015-11-04") &
                            date < as.Date("2020-03-19") & group == "diat"),
            aes(date, contribution),
            size = 1, color = "orange") +
  geom_line(data = filter(chem_join_plot, date > as.Date("2020-03-19") 
                          & group == "diat"),
            aes(date, contribution),
            size = 1, color = "orange") +
  geom_point(data = filter(chem_join_plot, group == "diat"),
             aes(date, contribution),
             pch = 21, fill = "white", color = "orange", size = 1.5, stroke = 1) +
  geom_line(data = filter(chem_join_plot, date > as.Date("2015-02-23") &
                            date < as.Date("2015-10-06")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2016-04-01") &
                            date <= as.Date("2016-10-02")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2017-04-20") &
                            date <= as.Date("2017-10-11")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2018-03-20") &
                            date <= as.Date("2018-10-30")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2019-03-12") &
                            date <= as.Date("2019-11-13")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2020-03-18") &
                            date <= as.Date("2020-09-22")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2021-02-23") &
                            date <= as.Date("2021-10-19")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2022-02-18") &
                            date <= as.Date("2022-10-26")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  geom_line(data = filter(chem_join_plot, date >= as.Date("2023-03-21") &
                            date <= as.Date("2023-11-07")),
            aes(date, y = bm_sum_total/scale_int),
            color = "black", size = 1.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale_int,
                                         name = bquote("Annual Int. TChla (mg" ~ m^-2*")"))) +
  scale_x_date(limits = as.Date(c("2015-01-01", "2024-01-01")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%b%y") +
  theme_bw() +
  labs(y = bquote("Diatoms (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(panel.grid.major.x =  element_line(color = "darkgrey", size = 0.5),
        panel.grid.minor.x =  element_line(color = "darkgrey", size = 0.5),
        legend.position = "none",
        legend.title = element_blank(),
        text = element_text(size = 30), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank()) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE))

ggsave(here("figures", "timeseries_5m_chemtax_integrated_diatom.png"),
        width = 16, height = 6, dpi = 300)
```


POC Data

```{r}
# https://community.rstudio.com/t/interpolation-using-varying-dates/29607/2
poc_model <- poc %>% 
  select(!...1) %>% 
  filter(date > "2015-01-01" & date < "2023-01-01")

#Working to convert data to two week average using linear fit so that dataset is consistent for cumulative sum.
ApproxFun_kg <- approxfun(x = poc_model$date, y = poc_model$poc_umol_kg)
ApproxFun_l <- approxfun(x = poc_model$date, y = poc_model$poc_umol)
Dates <- seq.Date(lubridate::ymd("2015-01-01"), lubridate::ymd("2022-12-31"),
                  by = 14)

LinearFit_kg <- ApproxFun_kg(Dates)
LinearFit_l <- ApproxFun_l(Dates)
head(LinearFit_kg)

```

```{r}
plot(poc_model$date, poc_model$poc_umol_kg)
lines(Dates, LinearFit_kg, col = "blue")
```

```{r}
#Making a dataframe with the interpolated POC timeseries - doing this for both umol/kg and umol/m3
poc_interp_kg <- as.data.frame(LinearFit_kg)

#Adding date
poc_interp_kg$date = Dates

#renaming columns
poc_interp_kg <- poc_interp_kg %>% 
  select(date, poc_14_kg = LinearFit_kg)

#umol/l
poc_interp_l <- as.data.frame(LinearFit_l)

#adding dates
poc_interp_l$date = Dates

#renaming columns
poc_interp_l <- poc_interp_l %>% 
  select(date, poc_14_l = LinearFit_l)
```

```{r}
#Plotting the interpolation versus the data.
poc_interp_kg %>% 
  ggplot() +
  # geom_line(data = poc, aes(x = date, y = poc_umol_kg), color = "black", size = 2) +
  geom_point(data = poc, aes(x = date, y = poc_umol_kg), color = "red",
             size = 1, fill = "white", pch = 21, stroke = 1.5) +
  geom_line(data = poc_interp_kg, aes(x = date, y = poc_14_kg), color = "blue") +
  geom_point(data = poc_interp_kg, aes(x = date, y = poc_14_kg), color = "blue") +
  theme_bw() +
  theme(text = element_text(size = 25), #35
        axis.text = element_text(colour = "black"),
        axis.title.x = element_blank())

ggsave(here("figures", "poc_interpolation_comparison_2023-05-13.png"),
       width = 12, height = 6, dpi = 300)  
```

```{r}
#Removing the 2020 COVID gap from the interpolated data
poc_interp_kg_gap <- poc_interp_kg %>% 
  filter(date < "2020-03-21" | date > "2020-05-13")
```

```{r}
#Calculating cumulative sum TChla with the umol/kg dataset
cu_sum_poc_kg <- poc_interp_kg_gap %>%
  drop_na() %>% 
  mutate(year = lubridate::year(date)) %>% 
  select(date, year, poc_14_kg) %>% 
  group_by(year) %>% 
  mutate(bm_sum_total_kg = cumsum(poc_14_kg)) %>%  
  ungroup() %>% 
  mutate(doy = lubridate::yday(date))

```

```{r}
#Selecting max value for Wiley's table
cu_sum_max_poc_kg <- cu_sum_poc_kg %>% 
  group_by(year) %>% 
  filter(bm_sum_total_kg == max(bm_sum_total_kg, na.rm = T)) %>% 
  ungroup()

```

```{r}
scale_pom2 <- 5

cu_sum_poc_kg %>%
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>%
  ggplot() +
  geom_area(data = filter(cu_sum_poc_kg, date > "2015-01-01" &
                            date < "2020-03-20"),
            aes(x = date, y = poc_14_kg), color = "gray", size = 0.2,
            alpha = 0.5) +
  geom_area(data = filter(cu_sum_poc_kg, date > "2020-05-13"),
            aes(x = date, y = poc_14_kg), color = "gray", size = 0.2,
            alpha = 0.5) +
  geom_point(aes(x = date, y = poc_14_kg), size = 0.3) +

  # geom_line(aes(date, y = bm_sum_total_kg/scale_pom2),
  #           color = "black", size = 1) +
  geom_line(data = filter(cu_sum_poc_kg, date > "2015-01-01" &
                            date < "2015-12-31"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  geom_line(data = filter(cu_sum_poc_kg, date >= "2016-01-01" &
                            date <= "2016-12-31"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  geom_line(data = filter(cu_sum_poc_kg, date >= "2017-01-01" &
                            date <= "2017-12-31"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  geom_line(data = filter(cu_sum_poc_kg, date >= "2018-01-01" &
                            date <= "2018-12-31"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  geom_line(data = filter(cu_sum_poc_kg, date >= "2019-01-01" &
                            date <= "2019-12-31"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  geom_line(data = filter(cu_sum_poc_kg, date >= "2020-01-01" &
                            date <= "2020-12-31"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  geom_line(data = filter(cu_sum_poc_kg, date >= "2021-01-01" &
                            date <= "2021-12-21"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  geom_line(data = filter(cu_sum_poc_kg, date >= "2022-01-01" &
                            date <= "2022-12-31"),
            aes(date, y = bm_sum_total_kg/scale_pom2),
            color = "black", size = 1.5) +
  # geom_point(aes(date, y = bm_sum/scale_pom), fill = "transparent", size = 1.5,
  #            pch = 21, stroke = 1) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale_pom2,
                                         name = bquote("CUSUM POC (μmol" ~ kg^-1*")"))) +
  scale_x_date(limits = as.Date(c("2015-03-18", "2024-01-01")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%b%y") +
  # coord_cartesian(xlim = as.Date(c("2015-03-18", "2023-05-09"))) +
  theme_bw() +
  labs(y = bquote("POC (μmol" ~ kg^-1*")")) +
  # scale_y_continuous(expand = c(0, 0), limits = c(0,12)) +
  # scale_x_date(breaks = scales::date_breaks("3 month"),
  #              labels = scales::date_format("%m/%y")) +
  theme(legend.position = c(0.1, 0.93),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        # strip.background = element_blank(),
        # strip.text.x = element_blank(),
        # panel.spacing = unit(2, "lines"),
        text = element_text(size = 25), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

ggsave(here("figures", "test_2024-05-13.png"),
        width = 15, height = 6, dpi = 300)
```


















































